### ISSUE TITLE
VRTK Climbing Game Builds hits invisible wall

### ISSUE THREAD

**Issue by corriejgreen** [ExtendRealityLtd/VRTK#1126]
### Environment

 * Github
 * VRTK 3.1.0
 * Unity 5.5.0f3
 * HTC Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)

### Steps to reproduce

Game Builds using the climbing rig from the climbing demo. On some game builds the user will select an object, try to launch themselves up onto a ledge or to an area, but will soon hit an invisible collider - feels like an invisible wall around the blue playspace grid if enabled.

### Expected behavior

The player should be able to launch themselves into space, to grab an object or complete an action.

### Current behavior

Sometimes - same assets used in another level work for example. Levels one works fine on the project but levels two and three SOMETIMES have this invisible wall issue on a game build, not unity editor runtime.

If anyone has a remote idea on what could be causing this do let me know, its possible ive changed something but the game works flawlessly in the engine but have this issue on game builds.

**Comment by thestonefox** [comment]
You need to provide better steps to reproduce. I have no idea from your steps how to recreate the issue,

**Comment by corriejgreen** [comment]
Will try and recreate with the standard example with climbing wall.

**Comment by thestonefox** [comment]
If it can't be recreated consistently then it becomes very difficult to debug unfortunately.

**Comment by corriejgreen** [comment]
![vrtk player hitting invisible wall bug](https://cloud.githubusercontent.com/assets/8880520/25529930/24dbed18-2c1c-11e7-8f2e-fadd3e866f87.PNG)
Still working on trying to recreate and have been for some time as we are wanting to release without this issue. Screenshot does show something though, the player has launched themselves forward then getting stuck in mid air, if they take a step in physical space they fall again.

Thanks for your time, but are there any attributes on the players collider mesh that could be linked to sticking to surfaces. The objects dont have material attributes like bounce etc so was curious if the player had it? It seems something related to the player hitting the play space!

Still working on it, but if theres any thing anyone can think of regarding player physic attributes that we can play around with and adjust values that would be a good start!

**Comment by corriejgreen** [comment]
Update: Managed to recreate quite simply in the test scene.

Attempt to grab a blue cube from an edge and proceed to throw yourself towards the edge or face. Not on top of but at the edge itself. After an attempt or two I was able to recreate quite easily. 

A demonstration of this can be found at the link below. I have attempted to try and debunk it myself for a month but no avail.

[link to bug here](http://imgur.com/a/OhBXs)

**Comment by thestonefox** [comment]
You need to provide steps to reproduce in an example scene

**Comment by corriejgreen** [comment]
1. Teleport to the blue wall found in the demo scene.
2. Grab the wall with the controllers below edge and throw your character to the edge itself. Found in the link here http://imgur.com/a/OhBXs
3. Again, grab the wall and gently throw yourself into the blue wall you grabbed. Your character will float in the air to where you threw yourself to, allowing you to walk around the placespace. 
4. When throwing yourself aim for the edge around neck height, this makes it easier to recreate.

Its very easy to recreate once you know how to throw yourself to the object. The GIF linked above is an visual representation on how to do it.

**Comment by mattboy64** [comment]
I'll try to repro it. Sounds like the falling state might be getting tripped up. Are you on latest @corriejgreen? I fixed a similar issue several months ago.

**Comment by corriejgreen** [comment]
@mattboy64 I think I'm a version behind. Just updated to latest and will experiment. Will update in the next day or two once I have resolved any conflicts.

**Comment by NeuroTR0PHY** [comment]
I believe I am experiencing the same thing in my game. I have found that if within a trigger the climbing is erratic (I will fall back to the ground when I attempt to propel myself upward or I might go flying back). If I turn off the two triggers in the level, all works fine.

**Comment by NeuroTR0PHY** [comment]
There is definitely something off with climbing and triggers. I have found that if I am already within a trigger and I start climbing (I am talking about climbing where you throw yourself upwards, i.e. you aren't always holding onto the wall), everything is fine, but if I hit a trigger above me while climbing and throwing myself upwards, I get sent back to the ground or the play area bucks around wildly.

**Comment by corriejgreen** [comment]
Update to this as i have just gotten around to importing the 3.1.0 > 3.2.0 

I have imported the latest version and still getting the issue, i should fall to the ground if the gameobject im on has fallen no? 

1) If i land on a moving gameobject, where is the check to fall to the ground as it isnt triggered
2) If i throw myself onto the object and land just on its edge (a cube) i get stuck there and it doesnt always push me ontop or let me fall.

Im still investigating, if anyone has any ideas please share. This is recreatable in the latest version of vrtk.

**Comment by bddckr** [comment]
Latest version of VRTK is [3.3.0](https://github.com/thestonefox/VRTK/tree/release/3.3.0-alpha), have a test with that. It won't probably change anything but then you are at least on the same version everyone else is on.

For troubleshooting [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) is a better support channel to use, GitHub issues aren't nice for discussions.

**Comment by corriejgreen** [comment]
On it @bddckr updated to the latest and working on repo. Have a month to solve the issue now.

Cheers

**Comment by thestonefox** [comment]
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.
